export const processNoData = [
  {
    section: "Assembly",
    subSection: [
      {
        name: "Block_Sub",
        processNo: [
          { label: "Block_Sub_ON", value: "BLOCKSUB_ON" },
          { label: "Crank_ON", value: "CRANK_ON" },
          { label: "Crank_S / N", value: "Crank S / N" },
          { label: "Block_S / N", value: "Block S / N" },
        ],
      },
      {
        name: "Head_Sub",
        processNo: [
          { label: "Head_bolt_NR", value: "HeadboltNR" },
          { label: "CamHousingSub_OFF", value: "CAMHOUSINGSIB_OFF" },
          { label: "CamHousing_S/N", value: "CamHousing S/N" },
          { label: "EX_cam_S / N", value: "EX cam S / N" },
          { label: "IN_cam_S / N", value: "IN cam S / N" },
          { label: "HeadSub_OFF", value: "HEADSUB_OFF" },
          { label: "Head_S / N", value: "Head S / N" },
        ],
      },
      { name: "MK_1", processNo: [{ label: "Main_ON", value: "MAIN_ON" }] },
      {
        name: "ET",
        processNo: [
          { label: "Fuel_Leak", value: "FuelLeak" },
          { label: "Walter_Leak", value: "WalterLeak" },
          { label: "Test_ON", value: "TEST_ON" },
          { label: "Oil_Leak", value: "OileLeak" },

          {
            label: "Engine_quality_information",
            value: "Engine quality information",
          },

          // { label: "EG_NO", value: "EGNO" },
        ],
      },
    ],
  },
  {
    section: "Machining",
    subSection: [
      {
        name: "Block Cylinder",
        processNo: [
          { label: "OP5", value: "B1_ENGRAVED" },
          { label: "OP150", value: "OP150" },

          { label: "OP160", value: "OP160" },
          { label: "OP170", value: "OP170" },
          { label: "OP180", value: "OP180" },
          { label: "OP190", value: "B3_OP190" },
          { label: "OP195AB", value: "B4_Finishing gantry" },

          { label: "OP200", value: "OP200" },
          { label: "OP210", value: "OP210" },
          { label: "OP220", value: "OP220" },
          { label: "OP230", value: "OP230" },
          { label: "OP235", value: "B5_OP235" },
          { label: "OP245", value: "OP245" },
          { label: "FG", value: "B7_OP990" },
        ],
      },
      {
        name: "Head Cylinder",
        processNo: [
          { label: "OP05", value: "H1_Material input/engraving" },

          { label: "OP10", value: "OP10" },
          { label: "OP20", value: "OP20" },
          { label: "OP30", value: "OP30" },
          { label: "OP50", value: "H2_OP050" },
          { label: "OP55", value: "H3_OP055" },
          { label: "OP80 A & B", value: "OP80 A & B" },
          { label: "OP90 A & B", value: "OP90 A & B" },
          { label: "OP100 A & B", value: "OP100 A & B" },
          { label: "OP100 A & B", value: "OP100 A & B" },
          { label: "OP110 A & B", value: "OP110 A & B" },
          { label: "OP120 A & B", value: "OP120 A & B" },
          { label: "OP140 A & B", value: "OP140 A & B" },
          { label: "OP150 A & B", value: "OP150 A & B" },
          { label: "OP160 A & B", value: "OP160 A & B" },
          { label: "OP170 A & B", value: "OP170 A & B" },
          { label: "OP175", value: "H4_Before transport OP80" },
          { label: "OP180 A & B", value: "OP180 A & B" },

          { label: "OP200", value: "OP200" },
          { label: "OP210", value: "OP210" },
          { label: "OP220", value: "OP220" },
          { label: "OP230", value: "OP230" },
          { label: "OP310", value: "H5_OP310" },
          { label: "FG", value: "H12_OP990" },
        ],
      },
      {
        name: "Crank Shaft",
        processNo: [
          { label: "OP02", value: "C1_Comaterial" },
          { label: "OP05", value: "OP05" },
          { label: "OP10", value: "OP10" },
          { label: "OP20", value: "OP20" },
          { label: "OP30", value: "OP30" },
          { label: "OP40", value: "OP40" },
          { label: "OP50", value: "OP50" },
          { label: "OP70", value: "OP70" },
          { label: "OP90", value: "OP90" },
          { label: "OP100", value: "OP100" },
          { label: "OP105", value: "OP105" },
          { label: "OP110", value: "OP110" },
          { label: "OP120", value: "OP120" },
          { label: "OP128", value: "OP128" },
          { label: "OP130", value: "OP130" },
          { label: "OP140", value: "C7_Gantry after OP140" },
          // { label: "OP150_170", value: "C3_OP150_170" },
          { label: "OP150_170", value: "OP150_170" },
          { label: "170 front Gantry", value: "C6_OP170 front gantry" },

          { label: "OP160", value: "OP160" },
          { label: "OP180", value: "OP180" },
          { label: "OP190", value: "OP190" },
          { label: "OP200", value: "OP200" },
          { label: "OP220", value: "C4_OP220" },
          { label: "FG", value: "C8_OP990" },
        ],
      },
    ],
  },
  {
    section: "Supplier part",
    subSection: [
      { name: "Shipment", processNo: ["S1", "S2"] },
      { name: "Head Cylinder ", processNo: [1, 2] },
      { name: "Crank Shaft", processNo: [1, 2] },
      { name: "Connecting rod", processNo: [1, 2] },
      { name: "Crank Case", processNo: [1, 2] },
      { name: "Cam housing", processNo: [1, 2] },
      { name: "Port Injector", processNo: [1, 2] },
      { name: "Pully Crank Shaft", processNo: [1, 2] },
    ],
  },
];
