export const processNo = [
  {
    section: "Assembly",
    subSection: [
      { name: "Shipment", processNo: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      { name: "FTB", processNo: [11, 21] },
      { name: "MTB", processNo: [1, 2] },
      { name: "Oil/water leak", processNo: [1, 2] },
      { name: "Fuel Leak", processNo: [1, 2] },
      { name: "CHS", processNo: [1, 2] },
      { name: "BS", processNo: [{label:'OPBS-1',value:'OPBS-1'}, {label:'OPBS-1',value:'OPBS-1'}, {label:'OPBS-1',value:'OPBS-1'}, {label:'OPBS-2',value:'OPBS-2'}, {label:'OPBS-2',value:'OPBS-2'}, {label:'OPBS-2',value:'OPBS-2'}, {label:'OPBS-2',value:'OPBS-2'}, {label:'OPBS-3',value:'OPBS-3'}, {label:'OPBS-3',value:'OPBS-3'}, {label:'OPBS-3',value:'OPBS-3'}, {label:'OPBS-3',value:'OPBS-3'}, {label:'OPBS-4',value:'OPBS-4'}, {label:'OPBS-4',value:'OPBS-4'}, {label:'OPBS-4',value:'OPBS-4'}, {label:'OPBS-4',value:'OPBS-4'}, {label:'OPBS-5',value:'OPBS-5'}, {label:'OPBS-5',value:'OPBS-5'}, {label:'OPBS-5',value:'OPBS-5'}, {label:'OPBS-5',value:'OPBS-5'}, {label:'OPBS-5',value:'OPBS-5'}, {label:'OPBS-5',value:'OPBS-5'}, {label:'OPBS-6',value:'OPBS-6'}] },
      { name: "PS", processNo: [1, 2] },
      { name: "SPS", processNo: [1, 2] },
      { name: "MK line", processNo: [1, 2] },
    ],
  },
  {
    section: "Machining",
    subSection: [
      {
        name: "Block Cylinder ",
        processNo: [
          { label: "OP5", value: "OP5" },
          { label: "OP150", value: "OP150" },
          { label: "OP150", value: "OP150" },
          { label: "OP150", value: "OP150" },
          { label: "OP160", value: "OP160" },
          { label: "OP170", value: "OP170" },
          { label: "OP180", value: "OP180" },
          { label: "OP190", value: "OP190" },
          { label: "OP195A", value: "OP195A" },
          { label: "OP195B", value: "OP195B" },
          { label: "OP200", value: "OP200" },
          { label: "OP210", value: "OP210" },
          { label: "OP220", value: "OP220" },
          { label: "OP230", value: "OP230" },
          { label: "OP230", value: "OP230" },
          { label: "OP230", value: "OP230" },
          { label: "OP235", value: "OP235" },
          { label: "OP235", value: "OP235" },
          { label: "OP235", value: "OP235" },
          { label: "OP235", value: "OP235" },
          { label: "OP245", value: "OP245" },
        ],
      },
      {
        name: "Head Cylinder ",
        processNo: [
          { label: "OP", value: "OP" },
          { label: "OP05", value: "OP05" },
          { label: "OP10", value: "OP10" },
          { label: "OP20", value: "OP20" },
          { label: "OP30", value: "OP30" },
          { label: "OP50", value: "OP50" },
          { label: "OP55", value: "OP55" },
          { label: "OP80 A & B", value: "OP80 A & B" },
          { label: "OP90 A & B", value: "OP90 A & B" },
          { label: "OP100 A & B", value: "OP100 A & B" },
          { label: "OP100 A & B", value: "OP100 A & B" },
          { label: "OP110 A & B", value: "OP110 A & B" },
          { label: "OP120 A & B", value: "OP120 A & B" },
          { label: "OP140 A & B", value: "OP140 A & B" },
          { label: "OP150 A & B", value: "OP150 A & B" },
          { label: "OP160 A & B", value: "OP160 A & B" },
          { label: "OP170 A & B", value: "OP170 A & B" },
          { label: "OP180 A & B", value: "OP180 A & B" },
          { label: "OP200", value: "OP200" },
          { label: "OP210", value: "OP210" },
          { label: "OP220", value: "OP220" },
          { label: "OP230", value: "OP230" },
        ],
      },
      {
        name: "Crank Shaft ",
        processNo: [
          { label: "OP02", value: "OP02" },
          { label: "OP05", value: "OP05" },
          { label: "OP10", value: "OP10" },
          { label: "OP20", value: "OP20" },
          { label: "OP30", value: "OP30" },
          { label: "OP40", value: "OP40" },
          { label: "OP50", value: "OP50" },
          { label: "OP70", value: "OP70" },
          { label: "OP90", value: "OP90" },
          { label: "OP100", value: "OP100" },
          { label: "OP105", value: "OP105" },
          { label: "OP110", value: "OP110" },
          { label: "OP120", value: "OP120" },
          { label: "OP128", value: "OP128" },
          { label: "OP130", value: "OP130" },
          { label: "OP140", value: "OP140" },
          { label: "OP150 & 170", value: "OP150 & 170" },
          { label: "OP160", value: "OP160" },
          { label: "OP180", value: "OP180" },
          { label: "OP190", value: "OP190" },
          { label: "OP200", value: "OP200" },
          { label: "OP220", value: "OP220" },
          { label: "OPFG", value: "OPFG" },
        ],
      },
    ],
  },
  {
    section: "Supplier part",
    subSection: [
      { name: "Shipment", processNo: ["S1", "S2"] },
      { name: "Head Cylinder ", processNo: [1, 2] },
      { name: "Crank Shaft", processNo: [1, 2] },
      { name: "Connecting rod", processNo: [1, 2] },
      { name: "Crank Case", processNo: [1, 2] },
      { name: "Cam housing", processNo: [1, 2] },
      { name: "Port Injector", processNo: [1, 2] },
      { name: "Pully Crank Shaft", processNo: [1, 2] },
    ],
  },
];
