export const ENGINE_FETCH = "ENGINE_FETCH" 
export const ENGINE_SUCCESS = "ENGINE_SUCCESS" 
export const ENGINE_FAIL = "ENGINE_FAIL" 
// 
export const SHIPPING_DATA_FETCH = "SHIPPING_DATA_FETCH" 
export const SHIPPING_DATA_SUCCESS = "SHIPPING_DATA_SUCCESS" 
export const SHIPPING_DATA_FAIL = "SHIPPING_DATA_FAIL" 
// 
export const SECTION ="SECTION"
export const SUB_SECTION= "SUB_SECTION" 
