export const PROCESS_FETCH = "PROCESS_FETCH";
export const PROCESS_SUCCESS = "PROCESS_SUCCESS";
export const PROCESS_FAILURE = "PROCESS_FAILURE ";
export const PROCESS3_FETCH = "PROCESS3_FETCH";
export const PROCESS3_SUCCESS = "PROCESS3_SUCCESS";
export const PROCESS3_FAILURE = "PROCESS3_FAILURE ";
export const SET_PROCESS_NO = "SET_PROCESS_NO";
export const PROCESS_ONE_DAY_FETCH = "PROCESS_ONE_DAY_FETCH";
export const PROCESS_ONE_DAY_SUCCESS = "PROCESS_ONE_DAY_SUCCESS";
export const PROCESS_ONE_DAY_FAILURE = "PROCESS_ONE_DAY_FAILURE ";
export const PROCESS_RANGE_FETCH = "PROCESS_RANGE_FETCH";
export const PROCESS_RANGE_SUCCESS = "PROCESS_RANGE_SUCCESS";
export const PROCESS_RANGE_FAILURE = "PROCESS_RANGE_FAILURE ";
export const PROCESS_ENGINE_FETCH = "PROCESS_ENGINE_FETCH";
export const PROCESS_ENGINE_SUCCESS = "PROCESS_ENGINE_SUCCESS";
export const PROCESS_ENGINE_FAILURE = "PROCESS_ENGINE_FAILURE ";
export const PROCESS_ENGINE_DATE_FAILURE = "PROCESS_ENGINE_DATE_FAILURE ";
export const PROCESS_ENGINE_DATE_FETCH = "PROCESS_ENGINE_DATE_FETCH";
export const PROCESS_ENGINE_DATE_SUCCESS = "PROCESS_ENGINE_DATE_SUCCESS";
export const SET_FROM_DATE="SET_FROM_DATE";
export const SET_TO_DATE="SET_TO_DATE";
export const SET_PROCESS_NAME = "SET_PROCESS_NAME";
export const PROCESS_CASTING_NO_FETCH = "PROCESS_CASTING_NO_FETCH";
export const PROCESS_CASTING_NO_SUCCESS = "PROCESS_CASTING_NO_SUCCESS";
export const PROCESS_CASTING_NO_FAILURE = "PROCESS_CASTING_NO_FAILURE ";
export const CLEAR = "CLEAR";





