export const PROCESS_FETCH = "PROCESS_FETCH";
export const PROCESS_SUCCESS = "PROCESS_SUCCESS";
export const PROCESS_FAILURE = "PROCESS_FAILURE ";
export const SET_PROCESS_NO = "SET_PROCESS_NO";
export const PROCESS_ONE_DAY_FETCH = "PROCESS_ONE_DAY_FETCH";
export const PROCESS_ONE_DAY_SUCCESS = "PROCESS_ONE_DAY_SUCCESS";
export const PROCESS_ONE_DAY_FAILURE = "PROCESS_ONE_DAY_FAILURE ";
export const PROCESS_RANGE_FETCH = "PROCESS_RANGE_FETCH";
export const PROCESS_RANGE_SUCCESS = "PROCESS_RANGE_SUCCESS";
export const PROCESS_RANGE_FAILURE = "PROCESS_RANGE_FAILURE ";
export const SET_FROM_DATE="SET_FROM_DATE";
export const SET_TO_DATE="SET_TO_DATE";




